# Use a Python base image
FROM python:3.12-slim

RUN apt-get update -qq -y && \
    apt-get install -y \
        libasound2 \
        libatk-bridge2.0-0 \
        libgtk-4-1 \
        libnss3 \
        unzip \
        xdg-utils \
        wget && \
    wget -q -O chrome-linux64.zip https://bit.ly/chrome-linux64-121-0-6167-85 && \
    unzip chrome-linux64.zip && \
    rm chrome-linux64.zip && \
    mv chrome-linux64 /opt/chrome/ && \
    ln -s /opt/chrome/chrome /usr/local/bin/ && \
    wget -q -O chromedriver-linux64.zip https://bit.ly/chromedriver-linux64-121-0-6167-85 && \
    unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver && \
    rm chromedriver-linux64.zip && \
    mv chromedriver /usr/local/bin/

# Set the working directory inside the container
WORKDIR /app

# Install the `uv` package
RUN pip install uv

# Copy the requirements.txt file into the container
COPY requirements.txt .
# COPY assistant /app

# Install all dependencies from requirements.txt
RUN uv pip install -r requirements.txt --system

EXPOSE 5000

# Command to execute app.py
# CMD ["python", "app.py"]
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "1200", "app:app"]